// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArrayField: typeof import("./src/components/ObjectField.vue")["default"]
    Code: typeof import("./src/components/CodePreview.vue")["default"]
    CodePreview: typeof import('./src/components/CodePreview.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCollapse: typeof import("element-plus/es")["ElCollapse"]
    ElCollapseItem: typeof import("element-plus/es")["ElCollapseItem"]
    ElCollapseTransition: typeof import('element-plus/es')['ElCollapseTransition']
    ElColorPicker: typeof import("element-plus/es")["ElColorPicker"]
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputInput: typeof import("element-plus/es")["ElInputInput"]
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    Enable: typeof import("./src/components/Enable.vue")["default"]
    FalseOrStringField: typeof import('./src/components/FalseOrStringField.vue')['default']
    FalseOrUnitField: typeof import('./src/components/FalseOrUnitField.vue')['default']
    FormWrapper: typeof import("./src/components/FormWrapper.vue")["default"]
    HelloWorld: typeof import("./src/components/HelloWorld.vue")["default"]
    InnerForm: typeof import('./src/components/InnerForm.vue')['default']
    ObjectField: typeof import('./src/components/ObjectField.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Setting: typeof import('./src/components/Setting.vue')['default']
    Unit: typeof import("./src/components/UnitField.vue")["default"]
    UnitField: typeof import('./src/components/UnitField.vue')['default']
  }
}
